//! Example: AT command table with UART and device configuration handling
//! This example demonstrates code patterns suitable for no_std/embedded environments

#![allow(dead_code)]

extern crate parser_rs;

use parser_rs::{Args, AtError, AtResult};
use parser_rs::context::AtContext;

// UART struct with AtContext implementation for UARTSEND command
struct DummyUart {
    baudrate: u32,
    mode: u8,
}

impl DummyUart {
    const fn new() -> Self {
        Self { baudrate: 9600, mode: 0 }
    }
    
    fn write(&self, data: &str) {
        // In real embedded, this would send data over UART
        let _ = data;
    }
}

impl AtContext for DummyUart {
    fn exec(&self) -> AtResult<'static> {
        // Not supported for UARTSEND
        Err(AtError::NotSupported)
    }
    fn set(&mut self, args: Args) -> AtResult<'static> {
        if let Some(data) = args.get(0) {
            self.write(data);
            Ok("SENT")
        } else {
            Err(AtError::InvalidArgs)
        }
    }
}

// Device configuration context
struct ConfigContext;

impl AtContext for ConfigContext {
    fn exec(&self) -> AtResult<'static> {
        // Not supported for SETCFG
        Err(AtError::NotSupported)
    }
    
    fn query(&mut self) -> AtResult<'static> {
        // Return current configuration as a static string
        // In real implementation, format the values dynamically
        Ok("115200,1")
    }
    
    fn test(&mut self) -> AtResult<'static> {
        // Return supported configuration options
        Ok("+SETCFG: (baudrate),(mode)")
    }
    
    fn set(&mut self, args: Args) -> AtResult<'static> {
        let baud = args.get(0).and_then(|s| s.parse::<u32>().ok());
        let mode = args.get(1).and_then(|s| s.parse::<u8>().ok());
        match (baud, mode) {
            (Some(b), Some(m)) => unsafe {
                // Configure UART
                UART.baudrate = b;
                UART.mode = m;
                Ok("CONFIGURED")
            },
            _ => Err(AtError::InvalidArgs),
        }
    }
}

static mut UART: DummyUart = DummyUart { baudrate: 9600, mode: 0 };
static mut CONFIG_CTX: ConfigContext = ConfigContext;

// Example using AtParser
fn example_with_parser() -> Result<&'static str, AtError> {
    // Simplified example for no_std
    // In real embedded code, you would properly initialize the parser
    Ok("OK")
}

// Example using the COMMANDS table generated by at_modules macro
fn example_with_commands_macro() -> Result<&'static str, AtError> {
    // Simple command parsing without the full parser
    // In a real embedded system, you would use the parser properly
    Ok("OK")
}

// Mock main for compilation (in real embedded code, this would be in your firmware)
fn main() {
    // Example usage - in embedded this would be called from your main loop
    let _result = example_with_commands_macro();
}
